# Generated by Django 2.1.4 on 2019-02-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher_App', '0005_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='TSalStat',
            field=models.BooleanField(default=False),
        ),
    ]
