# Generated by Django 2.1.4 on 2019-02-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher_App', '0006_teacher_tsalstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Tgender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
