# Generated by Django 2.1.4 on 2019-02-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_App', '0005_student_sfeestat'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Sgender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
