# Generated by Django 2.1.4 on 2019-02-05 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teacher_App', '0006_teacher_tsalstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aid', models.IntegerField()),
                ('AFname', models.CharField(max_length=20)),
                ('ALname', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('salary', models.IntegerField(max_length=6)),
                ('fee', models.IntegerField(max_length=5)),
                ('ATid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teacher_App.Teacher')),
            ],
        ),
    ]
